### PR TITLE
feat: Provide walking direction to the station

### PR DESCRIPTION
**Pull request by raphschwander**
- Tap on an station annotation to show a callout with details and button
- Tap on the left accessory control button to launch Maps app with navigation to the station
- Reminder: Direction started from the iPhone from Maps app is shown on the iWatch

| Departure mapView | Maps app |
| --- | --- |
| simulator screen shot 21 sept 2015 16 56 46 | simulator screen shot 21 sept 2015 16 56 58 |

### CODE REVIEW

**Comment by chregu** [comment]
cool, thanks a lot. Merged it. Had to adjust the name of the image. Seems to be case sensitive on my side. But apart from that, works fine

**Comment by raphschwander** [comment]
Fantastic ! I am glad I could help. I tried the app in live condition this weekend and everything worked well but I felt this feature was missing, especially if you wear an iWatch.
Btw, it would be great to be able to launch the navigation from the iWatch directly. If you need help with that part or anything else , let me know.

**Comment by chregu** [comment]
feel free to provide pull requests. We're happy about any help

You can already start navigation on the watch somehow. Force Touch on a "departure view" and then you have the map option. Maybe there's an easier way to do this, but I couldn't figure it out ;)

**Comment by raphschwander** [comment]
Oh right, I don't have that reflex to Force Touch everything yet :)
I am learning all the new capabilities of WatchKit for watchOS 2 at the moment. A lot of cool new features , with some that could definately be added to the TimeForCoffee watch extension. I ll see what I can do.

**Pull request merged**
